This is the policy notebook that I used for some basic exploratory analysis into the coronanet dataset.

In [21]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
pd.set_option('display.max_columns', 999)

In [22]:
df_all = pd.read_csv(r'coronanet_release_allvars.csv', parse_dates = ['date_updated'])
df_all

record_id  policy_id entry_type correct_type update_type  \
0      R_1gShvNnZtOkb4X1NA    3553952  new_entry     original         NaN   
1      R_3GrLmE8y71iEe17NA    2408864  new_entry     original         NaN   
2      R_1Hi5XBHB1zBOJc7NA    5424670  new_entry   correction         NaN   
3      R_3EQBDJGMTKwowKOAq    2272584  new_entry   correction         NaN   
4      R_1OoGDBSpbZQ02oANA    5468900  new_entry     original         NaN   
...                    ...        ...        ...          ...         ...   
31209  R_1K0WUazA1VYYZxVNA    9940508  new_entry     original         NaN   
31210  R_3fPEv3U7VviQZonNA    9950598  new_entry     original         NaN   
31211  R_2CBB0gC43BX2UJcBs    9973974  new_entry     original         NaN   
31212  R_2CBB0gC43BX2UJcCp    9973974  new_entry     original         NaN   
31213  R_2CBB0gC43BX2UJcAz    9973974  new_entry     original         NaN   

      update_level                                        description  \
0              NaN  Bahrain Health Ministry monitoring coronavirus...   
1              NaN  MoH of Barbados met in press conference to dis...   
2              NaN  On January 22, 2020, Canada implements screeni...   
3              NaN  China announced on January 22: to guide the pr...   
4              NaN  Xi'an, China announced that subway stations an...   
...            ...                                                ...   
31209          NaN  A report from 11 May, suggests it is not clear...   
31210          NaN  North Korea calling on Ministry of State Secur...   
31211          NaN  As of 21 April, the EU is coordinating and co-...   
31212          NaN  As of 21 April, the EU is coordinating and co-...   
31213          NaN  As of 21 April, the EU is coordinating and co-...   

      date_announced  date_start date_end         country ISO_A3 ISO_A2  \
0         2020-01-22  2020-01-22      NaN         Bahrain    BHR     BH   
1         2020-01-22  2020-01-22      NaN        Barbados    BRB     BB   
2         2020-01-22  2020-01-22      NaN          Canada    CAN     CA   
3         2020-01-22  2020-01-22      NaN           China    CHN     CN   
4         2020-01-22  2020-01-22      NaN           China    CHN     CN   
...              ...         ...      ...             ...    ...    ...   
31209     2020-05-11  2020-05-11      NaN           Nauru    NRU     NR   
31210     2020-02-11  2020-02-11      NaN     North Korea    PRK     KP   
31211     2020-04-21  2020-04-21      NaN  European Union    NaN    NaN   
31212     2020-04-21  2020-04-21      NaN  European Union    NaN    NaN   
31213     2020-04-21  2020-04-21      NaN  European Union    NaN    NaN   

      init_country_level  domestic_policy province   city  \
0               National                0      NaN    NaN   
1               National                0      NaN    NaN   
2               National                1      NaN    NaN   
3               National                0      NaN    NaN   
4              Municipal                0  Shaanxi  Xi'an   
...                  ...              ...      ...    ...   
31209           National                0      NaN    NaN   
31210           National                0      NaN    NaN   
31211           National                0      NaN    NaN   
31212           National                0      NaN    NaN   
31213           National                0      NaN    NaN   

                               type  \
0                 Health Monitoring   
1         Public Awareness Measures   
2                 Health Monitoring   
3         Public Awareness Measures   
4                           Hygiene   
...                             ...   
31209             Health Monitoring   
31210  Anti-Disinformation Measures   
31211              Health Resources   
31212              Health Resources   
31213              Health Resources   

                                            type_sub_cat type_text  \
0                                         

In [38]:
# df_all['compliance'].unique()
df_all['type'].nunique()

19

In [24]:
df = df_all[['policy_id', 'correct_type', 'date_start', 'country', 'ISO_A3', 'init_country_level', 'type', 'compliance']]
df

policy_id correct_type  date_start         country ISO_A3  \
0        3553952     original  2020-01-22         Bahrain    BHR   
1        2408864     original  2020-01-22        Barbados    BRB   
2        5424670   correction  2020-01-22          Canada    CAN   
3        2272584   correction  2020-01-22           China    CHN   
4        5468900     original  2020-01-22           China    CHN   
...          ...          ...         ...             ...    ...   
31209    9940508     original  2020-05-11           Nauru    NRU   
31210    9950598     original  2020-02-11     North Korea    PRK   
31211    9973974     original  2020-04-21  European Union    NaN   
31212    9973974     original  2020-04-21  European Union    NaN   
31213    9973974     original  2020-04-21  European Union    NaN   

      init_country_level                          type  \
0               National             Health Monitoring   
1               National     Public Awareness Measures   
2               National             Health Monitoring   
3               National     Public Awareness Measures   
4              Municipal                       Hygiene   
...                  ...                           ...   
31209           National             Health Monitoring   
31210           National  Anti-Disinformation Measures   
31211           National              Health Resources   
31212           National              Health Resources   
31213           National              Health Resources   

                                       compliance  
0          Voluntary/Recommended but No Penalties  
1                 Mandatory (Unspecified/Implied)  
2                 Mandatory (Unspecified/Implied)  
3                 Mandatory (Unspecified/Implied)  
4                 Mandatory (Unspecified/Implied)  
...                                           ...  
31209      Voluntary/Recommended but No Penalties  
31210  Mandatory with Legal Penalties (Jail Time)  
31211      Voluntary/Recommended but No Penalties  
31212      Voluntary/Recommended but No Penalties  
31213      Voluntary/Recommended but No Penalties  

[31214 rows x 8 columns]

In [25]:
df_US = df_all[df_all['country'] == 'United States of America']
df_US

record_id  policy_id entry_type correct_type update_type  \
26     R_3I9x0DQ8VYXqyIcNA    5268950  new_entry     original         NaN   
79     R_6xmbSctmqkjMA4VAq    4532513  new_entry     original         NaN   
166    R_3HYstneCw7PlFabNA    4818187  new_entry     original         NaN   
167    R_2Sph5l7qOwVbxv5NA    8404605  new_entry     original         NaN   
244    R_2y7MdTX5WXoiVVTNA     810670  new_entry     original         NaN   
...                    ...        ...        ...          ...         ...   
30270  R_2P8eiAj1XV8KoopNA    3874095  new_entry     original         NaN   
30287  R_1gdyC25xLGlP5H1Bv    3889409  new_entry     original         NaN   
30347  R_20SSxVTWSBpbIXBNA    1747784  new_entry     original         NaN   
30922  R_2th7AG4MUxPvFR0NA    5889302  new_entry     original         NaN   
31108  R_UF41z6I547dzhfPEb     872174  new_entry     original         NaN   

      update_level                                        description  \
26             NaN  On Jan 22, the Washington state Department of ...   
79             NaN  Nebraska, in the United States, releases Healt...   
166            NaN  On Jan 24, NY Governor Cuomo has directed the ...   
167            NaN  On Jan 24, NY State Health Departmenthas hoste...   
244            NaN  On Jan 26, the NYSDOH announced it is working ...   
...            ...                                                ...   
30270          NaN  On July 6, the Sturgis City Council in Sturgis...   
30287          NaN  US state Michigan creates new task force for e...   
30347          NaN  New Mexico, United States\nOn June 18, 2019, E...   
30922          NaN  On January 21, CDC activated its Emergency Ope...   
31108          NaN  On Jan 17, the New York State Department of He...   

      date_announced  date_start    date_end                   country ISO_A3  \
26        2020-01-22  2020-01-22         NaN  United States of America    USA   
79        2020-01-23  2020-01-23         NaN  United States of America    USA   
166       2020-01-24  2020-01-24         NaN  United States of America    USA   
167       2020-01-24  2020-01-24         NaN  United States of America    USA   
244       2020-01-26  2020-01-26         NaN  United States of America    USA   
...              ...         ...         ...                       ...    ...   
30270     2020-07-06  2020-08-13  2020-08-20  United States of America    USA   
30287     2020-05-29  2024-05-29  2024-05-29  United States of America    USA   
30347     2020-03-11  2019-12-31  2020-06-30  United States of America    USA   
30922     2020-01-21  2020-01-21         NaN  United States of America    USA   
31108     2020-01-17  2020-01-17         NaN  United States of America    USA   

      ISO_A2 init_country_level  domestic_policy      province     city  \
26        US         Provincial                1    Washington      NaN   
79        US         Provincial                0      Nebraska      NaN   
166       US         Provincial                0      New York      NaN   
167       US         Provincial                0      New York      NaN   
244       US         Provincial                0      New York      NaN   
...      ...                ...              ...           ...      ...   
30270     US          Municipal                0  South Dakota  Sturgis   
30287     US         Provincial                1      Michigan      NaN   
30347     US         Provincial                1    New Mexico      NaN   
30922     US           National                1           NaN      NaN   
31108     US         Provincial                1      New York      NaN   

                                                    type  \
26                                     Health Monitoring   
79                             Public Awareness Measures   
166                            Public Awareness Measures   
167                            Public Awareness Measures   
244                            Public Awa

In [26]:
df_US['entry_type'].unique()

array(['new_entry', 'update'], dtype=object)

In [27]:
df_US['update_type'].unique()

array([nan, 'Change of Policy', 'End of Policy'], dtype=object)

In [28]:
df_US['update_level'].unique()

array([nan, 'Strengthening', 'Relaxing',
       'Both Strengthening and Relaxing'], dtype=object)

In [29]:
df_US['init_country_level'].unique()

array(['Provincial', 'National', 'Municipal'], dtype=object)

In [30]:
df_US['domestic_policy'].unique()

array([1, 0], dtype=int64)

In [31]:
df_US_national = df_US[df_US['init_country_level'] == 'National']
df_US_national

record_id  policy_id entry_type correct_type update_type  \
315    R_wNrySUc4A1vSjJvNA    7983802  new_entry     original         NaN   
416    R_2DXMT1QWfZZqJyLBv    6167271  new_entry     original         NaN   
538    R_3iBTDadLRNY96X7Dz    7179112  new_entry     original         NaN   
607    R_2rMmgdR5NM9go2nNA    6672217  new_entry   correction         NaN   
946    R_3ewzSc50qEbECaGEb    3967471  new_entry     original         NaN   
...                    ...        ...        ...          ...         ...   
25841  R_3D6kNc5q3feedZqDz    7158863  new_entry     original         NaN   
25904  R_2qyo456Fk8vGIKCDz    6910124  new_entry     original         NaN   
28045  R_1mfKIAZPEf0zY6dNA    2340404  new_entry     original         NaN   
29913  R_1QK3HEqeseTZJZ6Ca    7589850  new_entry     original         NaN   
30922  R_2th7AG4MUxPvFR0NA    5889302  new_entry     original         NaN   

      update_level                                        description  \
315            NaN  US Health and Human Services Secretary declare...   
416            NaN  On January 29, 2020 President Donald J. Trump ...   
538            NaN  On January 31 the United States President sign...   
607            NaN  US government officials issue level 4 travel a...   
946            NaN  On Feb 15, 2020 the US announce that 17.8 tons...   
...            ...                                                ...   
25841          NaN  President Trump instituted a travel restrictio...   
25904          NaN  Entry to the United States is suspended, per P...   
28045          NaN  On March 22, 2020 the U.S. President issued a ...   
29913          NaN  On May 27 2020, the Centers for Disease Contro...   
30922          NaN  On January 21, CDC activated its Emergency Ope...   

      date_announced  date_start    date_end                   country ISO_A3  \
315       2020-01-31  2020-01-27         NaN  United States of America    USA   
416       2020-01-29  2020-01-29         NaN  United States of America    USA   
538       2020-01-31  2020-01-31         NaN  United States of America    USA   
607       2020-02-02  2020-02-02         NaN  United States of America    USA   
946       2020-02-15  2020-02-15         NaN  United States of America    USA   
...              ...         ...         ...                       ...    ...   
25841     2020-05-27  2020-05-27         NaN  United States of America    USA   
25904     2020-05-24  2020-05-28         NaN  United States of America    USA   
28045     2020-03-22  2020-06-22  2020-05-08  United States of America    USA   
29913     2020-05-27  2020-07-27         NaN  United States of America    USA   
30922     2020-01-21  2020-01-21         NaN  United States of America    USA   

      ISO_A2 init_country_level  domestic_policy province city  \
315       US           National                1      NaN  NaN   
416       US           National                1      NaN  NaN   
538       US           National                0      NaN  NaN   
607       US           National                0      NaN  NaN   
946       US           National                1      NaN  NaN   
...      ...                ...              ...      ...  ...   
25841     US           National                0      NaN  NaN   
25904     US           National                0      NaN  NaN   
28045     US           National                1      NaN  NaN   
29913     US           National                0      NaN  NaN   
30922     US           National                1      NaN  NaN   

                                                    type  \
315                             Declaration of Emergency   
416    New Task Force, Bureau or Administrative Confi...   
538                         External Border Restrictions   
607                         External Border Restrictions   
946                                     Health Resources   
...                                                  ...   
25841                       E

In [32]:
df_US_national['school_status'].unique()

array([nan], dtype=object)

In [35]:
df_all['school_status'].unique()

array([nan, 'Preschool or childcare facilities closed/locked down',
       'Primary Schools closed/locked down',
       'Secondary Schools closed/locked down',
       'Higher education institutions closed/locked down',
       'Primary Schools allowed to open with conditions',
       'Secondary Schools allowed to open with conditions',
       'Higher education institutions allowed to open with conditions',
       'Preschool or childcare facilities allowed to open with conditions',
       'NAclosed/locked down',
       'Preschool or childcare facilities allowed to open with no conditions',
       'Primary Schools allowed to open with no conditions',
       'Secondary Schools allowed to open with no conditions',
       'Higher education institutions allowed to open with no conditions'],
      dtype=object)

In [37]:
df_US['type'].unique()

array(['Health Monitoring', 'Public Awareness Measures',
       'New Task Force, Bureau or Administrative Configuration',
       'Declaration of Emergency', 'External Border Restrictions',
       'Health Resources', 'Anti-Disinformation Measures',
       'Other Policy Not Listed Above', 'Quarantine',
       'Restrictions of Mass Gatherings', 'Lockdown',
       'Closure and Regulation of Schools', 'Social Distancing',
       'Health Testing', 'Hygiene',
       'Restriction and Regulation of Businesses',
       'Restriction and Regulation of Government Services',
       'Internal Border Restrictions', 'Curfew'], dtype=object)